# Generated by Django 4.1.1 on 2022-12-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='lastname',
        ),
        migrations.AddField(
            model_name='blogger',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='fullname',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='blogger',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
