# Generated by Django 4.1.1 on 2022-12-10 17:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogger_firstname_remove_blogger_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogtext',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
