# Generated by Django 4.1.1 on 2022-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogger_education_blogger_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
