# Generated by Django 4.1.1 on 2022-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogger_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
