# Generated by Django 4.1.1 on 2022-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogger_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloglayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainfeatured', models.SlugField(max_length=200)),
                ('featuredone', models.SlugField(max_length=200)),
                ('featuredtwo', models.SlugField(max_length=200)),
                ('featuredthree', models.SlugField(max_length=200)),
                ('featuredfour', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blogger',
            name='image',
            field=models.ImageField(default=123, upload_to='images'),
            preserve_default=False,
        ),
    ]
