# Generated by Django 4.1.1 on 2022-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_bloglayout_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
