# Generated by Django 4.1.1 on 2022-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blogger_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglayout',
            name='featuredfour',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bloglayout',
            name='featuredone',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bloglayout',
            name='featuredthree',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bloglayout',
            name='featuredtwo',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bloglayout',
            name='mainfeatured',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
